In [39]:
import pandas as pd
import numpy as np

df = pd.read_csv('input.txt',sep = ' ',header = None)
sum_last_numbers = 0
for ii,row in df.iterrows():
    diff_iter = row.to_numpy()
    iter_count = 0

    #forward
    iterations = {0:diff_iter}
    while diff_iter.sum() != 0:
        iter_count += 1
        diff_iter = np.diff(diff_iter)
        iterations[iter_count] = diff_iter
    
    current_row = np.concatenate([iterations[iter_count],[0]])
    for iteration in range(iter_count,0,-1):
        next_row = iterations[iteration-1]
        
        number_to_add = next_row[-1]+current_row[-1]

        current_row = np.concatenate([next_row,[number_to_add]])

    sum_last_numbers += current_row[-1]

    # Backwards
    # for iterations in range(iter_count):

sum_last_numbers

1647269739

In [45]:
import pandas as pd
import numpy as np

df = pd.read_csv('input.txt',sep = ' ',header = None,dtype=np.int64)
sum_last_numbers = 0
for ii,row in df.iterrows():
    diff_iter = row.to_numpy()
    iter_count = 0

    #forward
    iterations = {0:diff_iter}
    while diff_iter.sum() != 0:
        iter_count += 1
        diff_iter = np.diff(diff_iter)
        iterations[iter_count] = diff_iter
    
    current_row = np.concatenate([[0],iterations[iter_count]])
    for iteration in range(iter_count,0,-1):
        next_row = iterations[iteration-1]
        
        number_to_add = next_row[0]-current_row[0]

        current_row = np.concatenate([[number_to_add],next_row])

    sum_last_numbers += current_row[0]

    # Backwards
    # for iterations in range(iter_count):

sum_last_numbers

[5 5 5 5] [0 0 0 0] 5
[16 21 26 31 36] [5 5 5 5 5] 11
[  8  24  45  71 102 138] [11 16 21 26 31 36] -3
[  3  11  35  80 151 253 391] [ -3   8  24  45  71 102 138] 6
[  9  12  23  58 138 289 542 933] [  6   3  11  35  80 151 253 391] 3
[  -1    8   20   43  101  239  528 1070 2003] [  3   9  12  23  58 138 289 542 933] -4
[  -4   -5    3   23   66  167  406  934 2004 4007] [  -4   -1    8   20   43  101  239  528 1070 2003] 0
[  14   10    5    8   31   97  264  670 1604 3608 7615] [   0   -4   -5    3   23   66  167  406  934 2004 4007] 14
[   13    27    37    42    50    81   178   442  1112  2716  6324 13939] [  14   14   10    5    8   31   97  264  670 1604 3608 7615] -1
[    5    18    45    82   124   174   255   433   875  1987  4703 11027
 24966] [   -1    13    27    37    42    50    81   178   442  1112  2716  6324
 13939] 6
[    9    14    32    77   159   283   457   712  1145  2020  4007  8710
 19737 44703] [    6     5    18    45    82   124   174   255   433   875  19

864